# Generated by Django 5.2.6 on 2025-09-14 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OfficerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portal.station')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_full_name', models.CharField(max_length=255)),
                ('owner_phone_number', models.CharField(max_length=20)),
                ('owner_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('owner_address', models.TextField(blank=True, null=True)),
                ('imei', models.CharField(db_index=True, max_length=15, unique=True)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('device_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('incident_date', models.DateField()),
                ('incident_time', models.TimeField()),
                ('incident_type', models.CharField(max_length=100)),
                ('incident_location', models.TextField(blank=True, null=True)),
                ('owner_id_proof', models.FileField(blank=True, null=True, upload_to='proofs/ids/')),
                ('device_carton_photo', models.FileField(blank=True, null=True, upload_to='proofs/cartons/')),
                ('device_receipt', models.FileField(blank=True, null=True, upload_to='proofs/receipts/')),
                ('transaction_ref', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Stolen', 'Stolen'), ('Recovered', 'Recovered'), ('Pending', 'Pending Review')], default='Stolen', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portal.station')),
            ],
        ),
    ]
